using System;
using System.Collections.Generic;

namespace SigurAPI.tcdbmain
{
    public partial class Accessrule
    {
        public int Id { get; set; }
        public string? Extid { get; set; }
        public int Extsourceid { get; set; }
        public string? Name { get; set; }
        public byte[]? Description { get; set; }
        public string? Ruletype { get; set; }
        public int? Poweridx { get; set; }
        public DateTime? Startdate { get; set; }
        public DateTime? Enddate { get; set; }
        public string? Status { get; set; }
        public DateTime? Createdtime { get; set; }
        public DateTime? Deletedtime { get; set; }
        public bool? ServsyncExported { get; set; }
        public int? Nrules { get; set; }
        public int? Nspecrules { get; set; }
        public bool? Stdweekmode { get; set; }
        public byte[]? Rule0 { get; set; }
        public byte[]? Rule1 { get; set; }
        public byte[]? Rule2 { get; set; }
        public byte[]? Rule3 { get; set; }
        public byte[]? Rule4 { get; set; }
        public byte[]? Rule5 { get; set; }
        public byte[]? Rule6 { get; set; }
        public byte[]? Rule7 { get; set; }
        public byte[]? Rule8 { get; set; }
        public byte[]? Rule9 { get; set; }
        public byte[]? Rule10 { get; set; }
        public byte[]? Rule11 { get; set; }
        public byte[]? Rule12 { get; set; }
        public byte[]? Rule13 { get; set; }
        public byte[]? Rule14 { get; set; }
        public byte[]? Rule15 { get; set; }
        public byte[]? Rule16 { get; set; }
        public byte[]? Rule17 { get; set; }
        public byte[]? Rule18 { get; set; }
        public byte[]? Rule19 { get; set; }
        public byte[]? Rule20 { get; set; }
        public byte[]? Rule21 { get; set; }
        public byte[]? Rule22 { get; set; }
        public byte[]? Rule23 { get; set; }
        public byte[]? Rule24 { get; set; }
        public byte[]? Rule25 { get; set; }
        public byte[]? Rule26 { get; set; }
        public byte[]? Rule27 { get; set; }
        public byte[]? Rule28 { get; set; }
        public byte[]? Rule29 { get; set; }
        public byte[]? Rule30 { get; set; }
        public byte[]? Rule31 { get; set; }
        public DateTime? Specdate0 { get; set; }
        public byte[]? Specrule0 { get; set; }
        public DateTime? Specdate1 { get; set; }
        public byte[]? Specrule1 { get; set; }
        public DateTime? Specdate2 { get; set; }
        public byte[]? Specrule2 { get; set; }
        public DateTime? Specdate3 { get; set; }
        public byte[]? Specrule3 { get; set; }
        public DateTime? Specdate4 { get; set; }
        public byte[]? Specrule4 { get; set; }
        public DateTime? Specdate5 { get; set; }
        public byte[]? Specrule5 { get; set; }
        public DateTime? Specdate6 { get; set; }
        public byte[]? Specrule6 { get; set; }
        public DateTime? Specdate7 { get; set; }
        public byte[]? Specrule7 { get; set; }
        public DateTime? Specdate8 { get; set; }
        public byte[]? Specrule8 { get; set; }
        public DateTime? Specdate9 { get; set; }
        public byte[]? Specrule9 { get; set; }
        public DateTime? Specdate10 { get; set; }
        public byte[]? Specrule10 { get; set; }
        public DateTime? Specdate11 { get; set; }
        public byte[]? Specrule11 { get; set; }
        public DateTime? Specdate12 { get; set; }
        public byte[]? Specrule12 { get; set; }
        public DateTime? Specdate13 { get; set; }
        public byte[]? Specrule13 { get; set; }
        public DateTime? Specdate14 { get; set; }
        public byte[]? Specrule14 { get; set; }
        public DateTime? Specdate15 { get; set; }
        public byte[]? Specrule15 { get; set; }
        public DateTime? Specdate16 { get; set; }
        public byte[]? Specrule16 { get; set; }
        public DateTime? Specdate17 { get; set; }
        public byte[]? Specrule17 { get; set; }
        public DateTime? Specdate18 { get; set; }
        public byte[]? Specrule18 { get; set; }
        public DateTime? Specdate19 { get; set; }
        public byte[]? Specrule19 { get; set; }
        public DateTime? Specdate20 { get; set; }
        public byte[]? Specrule20 { get; set; }
        public DateTime? Specdate21 { get; set; }
        public byte[]? Specrule21 { get; set; }
        public DateTime? Specdate22 { get; set; }
        public byte[]? Specrule22 { get; set; }
        public DateTime? Specdate23 { get; set; }
        public byte[]? Specrule23 { get; set; }
        public DateTime? Specdate24 { get; set; }
        public byte[]? Specrule24 { get; set; }
        public DateTime? Specdate25 { get; set; }
        public byte[]? Specrule25 { get; set; }
        public DateTime? Specdate26 { get; set; }
        public byte[]? Specrule26 { get; set; }
        public DateTime? Specdate27 { get; set; }
        public byte[]? Specrule27 { get; set; }
        public DateTime? Specdate28 { get; set; }
        public byte[]? Specrule28 { get; set; }
        public DateTime? Specdate29 { get; set; }
        public byte[]? Specrule29 { get; set; }
        public DateTime? Specdate30 { get; set; }
        public byte[]? Specrule30 { get; set; }
        public DateTime? Specdate31 { get; set; }
        public byte[]? Specrule31 { get; set; }
        public bool? Boolparam1 { get; set; }
        public bool? Boolparam2 { get; set; }
        public bool? Boolparam3 { get; set; }
        public bool? Boolparam4 { get; set; }
        public bool? SpecOpreqa { get; set; }
        public bool? SpecOpreqb { get; set; }
        public string? SpecExtreadera { get; set; }
        public string? SpecExtreaderb { get; set; }
        public bool? SpecDpassa { get; set; }
        public bool? SpecDpassb { get; set; }
        public bool? SpecReqpina { get; set; }
        public bool? SpecReqpinb { get; set; }
        public bool? SpecEscorta { get; set; }
        public bool? SpecEscortb { get; set; }
        public int? SpecEscortRuleid { get; set; }
        public int? SpecEscortProb { get; set; }
        public string? SpecDreadAction { get; set; }
        public int? SpecPayitema { get; set; }
        public int? SpecPayitemb { get; set; }
        public string? LprpolicyA { get; set; }
        public string? LprpolicyB { get; set; }
        public bool? SpecExptimecollect { get; set; }
        public int? AlkoProba { get; set; }
        public int? AlkoProbb { get; set; }
        public bool? AlkoAllowdrunka { get; set; }
        public bool? AlkoAllowdrunkb { get; set; }
        public int? AlkoThr { get; set; }
        public bool? OverrideWt { get; set; }
        public string? Wtmode { get; set; }
        public byte[]? BreakType { get; set; }
        public bool? Guest { get; set; }
        public int? ParkingTariffId { get; set; }
        public string? Sideparam0 { get; set; }
        public string? FaceiA { get; set; }
        public string? FaceiB { get; set; }
        public string FacevA { get; set; } = null!;
        public string FacevB { get; set; } = null!;
        public int? WarnTempA { get; set; }
        public int? AlertTempA { get; set; }
        public int? WarnTempB { get; set; }
        public int? AlertTempB { get; set; }
        public string MaskvA { get; set; } = null!;
        public string MaskvB { get; set; } = null!;
        public string? CondType { get; set; }
        public string? CondSearchFor { get; set; }
        public string? CondSearchWhere { get; set; }
        public string? DeploymentId { get; set; }
    }
}
